title: Punith kumar B
description: Aspiring Data Analyst skilled in SQL, Excel, and Python, passionate about turning raw data into meaningful insights.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
